language: objective-c
osx_image: xcode7.1

script:
  - xcodebuild -project MarvelApiClient.xcodeproj -scheme MarvelApiClient build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6s Plus'