language: objective-c
osx_image: xcode8

before_install:
  - gem install xcpretty
  - gem install cocoapods
  - pod repo update --silent

install:
  - pod install

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace MarvelApiClient.xcworkspace -scheme 'MarvelApiClient' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
